name: Daily check in

on:
  schedule:
    - cron: "0 22 * * *" # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

jobs:
  check-in:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - cookie: ${{ secrets.COOKIE }}
            games: ${{ vars.GAMES }}
          - cookie: ${{ secrets.COOKIE1 }}
            games: ${{ vars.GAMES1 }}
          - cookie: ${{ secrets.COOKIE2 }}
            games: ${{ vars.GAMES2 }}
          - cookie: ${{ secrets.COOKIE3 }}
            games: ${{ vars.GAMES3 }}
          - cookie: ${{ secrets.COOKIE4 }}
            games: ${{ vars.GAMES4 }}
          - cookie: ${{ secrets.COOKIE5 }}
            games: ${{ vars.GAMES5 }}
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check In
        run: node index.js ${{ matrix.config.games }}
        env:
          COOKIE: ${{ matrix.config.cookie }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USER: ${{ secrets.DISCORD_USER }}
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
